use std::collections::HashMap;

use crate::theme_v3::{ResolvedColor, ResolvedThemeV3};

#[derive(Debug, thiserror::Error)]
pub enum HyprlandEmitError {
    #[error("theme is missing shim `{0}` required by the hyprland target mapping")]
    MissingShim(String),
}

/// Hyprland include snippet: `general { col… = rgba(…) }` and optional `decoration { shadow { … } }`.
///
/// `shim_to_native` values:
/// - `col.*` — emitted inside `general`
/// - `decoration.shadow.*` — emitted under `decoration { shadow { … } }`
pub fn render_hyprland_decorations(
    resolved: &ResolvedThemeV3,
    shim_to_native: &HashMap<String, String>,
) -> Result<String, HyprlandEmitError> {
    let mut general: Vec<(String, String)> = Vec::new();
    let mut shadow: Vec<(String, String)> = Vec::new();

    for (shim, native_key) in shim_to_native.iter() {
        let color = resolved
            .colors
            .get(shim.as_str())
            .ok_or_else(|| HyprlandEmitError::MissingShim((*shim).clone()))?;
        let rgba = rgba8(color);

        if let Some(rest) = native_key.strip_prefix("decoration.shadow.") {
            shadow.push((rest.to_string(), rgba));
        } else {
            general.push((native_key.clone(), rgba));
        }
    }

    general.sort_by(|a, b| a.0.cmp(&b.0));
    shadow.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("# Generated by chromamancer — border / decoration colors (see specs/hyprland-decorations.md)\n");
    out.push_str(&format!("# theme: {}\n", resolved.name));

    if !general.is_empty() {
        out.push_str("general {\n");
        for (k, rgba) in &general {
            out.push_str(&format!("    {k} = rgba({rgba})\n"));
        }
        out.push_str("}\n");
    }

    if !shadow.is_empty() {
        out.push_str("\ndecoration {\n    shadow {\n");
        for (k, rgba) in &shadow {
            out.push_str(&format!("        {k} = rgba({rgba})\n"));
        }
        out.push_str("    }\n}\n");
    }

    Ok(out)
}

fn rgba8(c: &ResolvedColor) -> String {
    match c {
        ResolvedColor::Transparent => "00000000".to_string(),
        ResolvedColor::Rgba { r, g, b, a } => format!("{:02x}{:02x}{:02x}{:02x}", r, g, b, a),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme_v3::resolve_theme_v3_from_str;

    #[test]
    fn borders_general_block() {
        let theme = r##"{
            "metadata": { "schema_version": "3", "name": "t", "version": "1" },
            "tokens": { "a": "#405495FF", "b": "#302947FF" },
            "shim_assign": { "chrome_focus": "a", "dark": "b" }
        }"##;
        let resolved = resolve_theme_v3_from_str(theme).unwrap();
        let mut map = HashMap::new();
        map.insert("chrome_focus".into(), "col.active_border".into());
        map.insert("dark".into(), "col.inactive_border".into());
        let s = render_hyprland_decorations(&resolved, &map).unwrap();
        assert!(s.contains("col.active_border = rgba(405495ff)"));
        assert!(s.contains("col.inactive_border = rgba(302947ff)"));
        assert!(s.contains("general {"));
    }

    #[test]
    fn nested_shadow_color() {
        let theme = r##"{
            "metadata": { "schema_version": "3", "name": "t", "version": "1" },
            "tokens": { "s": "#01021280" },
            "shim_assign": { "background": "s" }
        }"##;
        let resolved = resolve_theme_v3_from_str(theme).unwrap();
        let mut map = HashMap::new();
        map.insert("background".into(), "decoration.shadow.color".into());
        let s = render_hyprland_decorations(&resolved, &map).unwrap();
        assert!(s.contains("decoration {"));
        assert!(s.contains("shadow {"));
        assert!(s.contains("color = rgba(01021280)"));
    }
}
