use std::collections::HashMap;

use crate::theme_v3::ResolvedThemeV3;

#[derive(Debug, thiserror::Error)]
pub enum KittyEmitError {
    #[error("theme is missing shim `{0}` required by the kitty target mapping")]
    MissingShim(String),
    #[error("shim `{shim}` resolves to transparent; kitty does not support that for `{native_key}`")]
    TransparentColor { shim: String, native_key: String },
}

/// Build a kitty.conf snippet: one `native_key  #hex` per line (sorted by native_key).
pub fn render_kitty_colors(
    resolved: &ResolvedThemeV3,
    shim_to_native: &HashMap<String, String>,
) -> Result<String, KittyEmitError> {
    let mut lines: Vec<(String, String)> = Vec::new();
    for (shim, native_key) in shim_to_native.iter() {
        let color = resolved.colors.get(shim.as_str()).ok_or_else(|| {
            KittyEmitError::MissingShim((*shim).clone())
        })?;
        let hex = color.to_kitty_hex().ok_or_else(|| KittyEmitError::TransparentColor {
            shim: (*shim).clone(),
            native_key: native_key.clone(),
        })?;
        lines.push((native_key.clone(), hex));
    }
    lines.sort_by(|a, b| a.0.cmp(&b.0));
    let mut out = String::new();
    out.push_str("# Generated by chromamancer — do not edit by hand.\n");
    out.push_str(&format!("# theme: {}\n", resolved.name));
    for (k, hex) in lines {
        out.push_str(&format!("{k} {hex}\n"));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme_v3::resolve_theme_v3_from_str;

    #[test]
    fn izar_fixture_generates_snippet() {
        let theme = r##"{
            "metadata": { "schema_version": "3", "name": "izar", "version": "0.1.0" },
            "tokens": { "void": "#010212FF", "foam": "#d7cadcFF", "accent": "#6abab5FF" },
            "shim_assign": {
                "background": "void",
                "foreground": "foam",
                "cursor": "accent",
                "cursor_text": "void",
                "palette_0": "void",
                "palette_1": "void",
                "palette_2": "void",
                "palette_3": "void",
                "palette_4": "void",
                "palette_5": "void",
                "palette_6": "foam",
                "palette_7": "foam",
                "palette_8": "void",
                "palette_9": "void",
                "palette_10": "void",
                "palette_11": "void",
                "palette_12": "void",
                "palette_13": "void",
                "palette_14": "foam",
                "palette_15": "foam"
            }
        }"##;
        let resolved = resolve_theme_v3_from_str(theme).unwrap();
        let mut map = HashMap::new();
        map.insert("background".into(), "background".into());
        map.insert("foreground".into(), "foreground".into());
        let s = render_kitty_colors(&resolved, &map).unwrap();
        assert!(s.contains("background #010212"));
        assert!(s.contains("foreground #d7cadc"));
    }
}
